tasks:
  - name: Install dependencies
    init: |
      cargo install just
      just dev-install
      just build
    command: mdbook serve docs/ --open

ports:
  # docs
  - port: 3000
    onOpen: open-browser

vscode:
  extensions:
    - rust-lang.rust-analyzer
    - xoronic.pestfile
