tasks:
  - name: Install just
    init: cargo install just
  - name: Install dependencies
    init: just dev-install
  - name: Serve mdbook
    command: mdbook serve docs/ --open

ports:
  # docs
  - port: 3000
    onOpen: open-browser
