[package]
name = "cli"
authors = ["Joshua Price <jwpjr567@gmail.com>"]
version = "0.1.0"
edition = "2021"

[[bin]]
name = "lem"
path = "src/main.rs"

[dependencies]
clap = { version = "3.1.2", features = ["cargo", "derive"] }
interpreter = { path = "../interpreter" }
